#! /bin/bash

app=gplayweb

#retrieve arguments
domain=$1
path=$2
admin=$3
password=$4
is_public=$5

port=8888

# Remove trailing slash
#[ "$path" != "/" ] && path=${path%/}

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
[[ ! $? -eq 0 ]] &&  exit 1

# Check user
sudo yunohost user list --json | grep -q "\"username\": \"$admin\""
[[ ! $? -eq 0 ]] && echo "Wrong user" && exit 1

# Get first available port
sudo yunohost app checkport $port
while [[ ! $? -eq 0 ]]; do
	port=$((port+1))
	sudo yunohost app checkport $port
done

# Save app settings
sudo yunohost app setting $app admin -v "$admin"
sudo yunohost app setting $app is_public -v "$is_public"
sudo yunohost app setting $app domain -v "$domain"
sudo yunohost app setting $app path -v "$path"

# Install gplaycli
sudo apt-get update -qq
sudo apt-get install python-dev libffi-dev python-pip -y
sudo pip install six --upgrade
sudo pip install gplaycli
# Update all dependencies
sudo pip install gplaycli --upgrade

# Install gplayweb
sudo pip install gplayweb
# Update all dependencies
sudo pip install gplayweb --upgrade
sudo mkdir /etc/gplayweb
sudo cp ../conf/gplayweb.conf /etc/gplayweb/gplayweb.conf
sudo sed -i "s/YNH_PORT/$port/g" /etc/gplayweb/gplayweb.conf
sudo sed -i "s@YNH_EXAMPLE_PATH@$path@g" /etc/gplayweb/gplayweb.conf
sudo mkdir -p /opt/gplayweb/repo
sudo adduser gplayweb --disabled-password --gecos ""

#configure nginx settings
folder_path=${path%/}
sudo sed -i "s@YNH_EXAMPLE_PATH@$path@g" ../conf/nginx.conf
sudo sed -i "s@YNH_PORT@$port@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# If app is private, remove url to SSOWat conf from skipped_uris
[ "$is_public" = "No" ] && sudo yunohost app setting $app unprotected_uris -d

#adding admin to the allowed users
sudo yunohost app addaccess $app -u $admin

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf
sudo service gplayweb start
