#! /bin/bash

app="gplayweb"

#retrieve arguments
domain="$1"
path="$2"
admin="$3"
password="$4"
is_public="$5"

port=8888

# Remove trailing slash
#[ "$path" != "/" ] && path=${path%/}

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
[[ ! $? -eq 0 ]] &&  exit 1

# Check user
sudo yunohost user list --json | grep -q "\"username\": \"$admin\""
[[ ! $? -eq 0 ]] && echo "Wrong user" && exit 1

# Get first available port
sudo yunohost app checkport $port
while [[ ! $? -eq 0 ]]; do
	port=$((port+1))
	sudo yunohost app checkport $port
done

final_path=/opt/yunohost/gplayweb

# Save app settings
sudo yunohost app setting $app admin -v "$admin"
sudo yunohost app setting $app is_public -v "$is_public"
sudo yunohost app setting $app domain -v "$domain"
sudo yunohost app setting $app path -v "$path"

# Check Swap
if [ $(sudo swapon -s | wc -l) = 1 ];
then
	# It is NOT possible to setup a swap file on a tmpfs filesystem
	mount | grep /tmp | grep tmpfs > /dev/null 2>&1
	if [ $? = 1 ];
	then
		tmp_swap_file=/tmp/gplayweb_swapfile
	else
		tmp_swap_file=/var/cache/gplayweb_swapfile
	fi
	sudo dd if=/dev/zero of=$tmp_swap_file bs=1M count=256
	sudo chmod 600 $tmp_swap_file
	sudo mkswap $tmp_swap_file
	sudo swapon $tmp_swap_file
fi


# Init virtualenv
if [ ! -d $final_path ];
then
        sudo mkdir -p $final_path
fi

# Install gplaycli
sudo apt-get update -qq
sudo apt-get install python-dev libffi-dev python-pip python-virtualenv fdroidserver -y
#sudo virtualenv $final_path
sudo virtualenv --system-site-packages $final_path
sudo bash -c "source $final_path/bin/activate && pip install -r ../conf/requirements.txt"


# Install gplayweb
sudo bash -c "source $final_path/bin/activate && pip install gplayweb --upgrade"
sudo mkdir /etc/gplayweb/
sudo cp ../conf/gplayweb.conf /etc/gplayweb/gplayweb.conf
sudo sed -i "s/YNH_PORT/$port/g" /etc/gplayweb/gplayweb.conf
sudo sed -i "s@YNH_EXAMPLE_PATH@$path@g" /etc/gplayweb/gplayweb.conf

sudo adduser gplayweb --disabled-password --gecos ""
sudo mkdir -p /var/www/gplayweb/repo
sudo chown gplayweb. /var/www/gplayweb -R
sudo su - gplayweb -c "cd /var/www/gplayweb/ && fdroid init" 

#configure nginx settings
folder_path=${path%/}
sudo sed -i "s@YNH_EXAMPLE_PATH@$path@g" ../conf/nginx.conf
sudo sed -i "s@YNH_PORT@$port@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# If app is private, remove url to SSOWat conf from skipped_uris
[ "$is_public" = "No" ] && sudo yunohost app setting $app unprotected_uris -d
sudo yunohost app setting $app skipped_uris -v "/repo"

# Fix bug ssl and system request for fdroid
sudo patch /opt/yunohost/gplayweb/local/bin/gplayweb ../conf/gplayweb.diff
sudo patch /opt/yunohost/gplayweb/local/lib/python2.7/site-packages/ext_libs/googleplay_api/googleplay.py ../conf/googleplay.diff

# Install Crontab
sudo cp ../conf/crontab /etc/cron.daily/gplaycli

# Systemd
sudo cp ../conf/gplayweb.service /lib/systemd/system/
sudo systemctl enable gplayweb.service
sudo systemctl start gplayweb.service

#adding admin to the allowed users
sudo yunohost app addaccess $app -u $admin

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf
