#! /bin/bash

app=gplayweb
domain=$(sudo yunohost app setting $app domain)

sudo service gplayweb stop
sudo rm -Rf /opt/yunohost/gplayweb
sudo rm -rf /etc/gplayweb 
sudo rm -rf /home/gplayweb
sudo rm -rf /var/www/gplayweb
sudo rm -rf /etc/nginx/conf.d/$domain.d/$app.conf
sudo rm -f /tmp/.cache-gplayweb

sudo rm /etc/cron.daily/gplaycli

sudo systemctl disable gplayweb.service

sudo rm /lib/systemd/system/gplayweb.service
sudo deluser gplayweb

sudo nginx -s reload
sudo yunohost app ssowatconf
